export const ProhibitedWords = [
    'rafa',
    'filhinha de papai',
    'burguesa',
    'burguesinha',
    'patricinha',
    'rica',
    'mimada',
    'mimadinha',
    'jaraguá do sul',
    'jaragua',
    'se acha',
    'mulherzinha',
    'feminazi',
    'milionaria',
    'papai',
    'herdeira',
    'escrota',
    'fake',
    'falsa',
    'gostosa',
    'paty',
    'louca',
    'chata',
    'doida',
    'péssimo',
    'péssima',
    'menininha',
    'se acha',
    'se achando',
    'como assim',
    'odiei',
    'insuportável',
    'patty',
    'estranho',
    'faltou',
    'ryca',
    'bilioaria',
    'herdeira',
    'herdar',
    'herança',
    'feminista',
    'macho',
    'na cozinha',
    'falsa',
    'falso',
    'credo',
    'horrível',
    'fraca',
    'fraco',
    'não entendi',
    'nao gostei',
    'sem sentido',
    'não concordo',
    'discordo',
    'ganha',
    'nao acredito',
    'não acredito',
    'egirl',
    'e-girl',
    'pack',
    'perdi',
    'piada',
    'inutil',
    'patetico',
    'onlyfuns',
    'onlyfans',
    'puta',
    'gostosa',
    'nojenta',
    'nojento',
    'patetica',
    'zuado',
    'zuada',
    'lixo',
    'rica',
    'rico'
]